### ISSUE TITLE
Inquires about MultiAtlasTT

### ISSUE THREAD

**Issue by zqsha** [faskowit/multiAtlasTT#3]
Hi faskowit,

Thank you for developing such an amazing toolbox and sharing it with us. I just want to confirm a question.

1. After finishing recon-all, I should employ mris_ca_label with your new update .gcs files, like this:
mris_ca_label \
 -orig white \
 -novar \
 -t atlas_data/hcp-mmp-b/lh.hcp-mmp-b_colortab.txt \
 sub01 \
 lh \
 sub01/surf/sphere.reg \
 hcp-mmp-b/lh.hcp-mmp-b_5p3.gcs \
 $SUBJECTS_DIR/sub01/label/lh.aparc.mmp.annot 
Is this the correct way to employ gcs files?

2. I found two .gcs files in hcp-mmp.b folders, including lh.hcp-mmp-b_5p3.gcs and lh.hcp-mmp-b_6p0.gcs. What's the difference?

Thank you so much.
Best,
Zhiqiang

**Comment by faskowit** [comment]
Thanks for the interest in the tools! 

The script here: https://github.com/faskowit/multiAtlasTT/blob/master/example_run_maTT2.sh  will apply those .gcs file for you (if you edit the script to point to the correct locations of atlas_data and that subject on your own computer).  The gcs files were separately trained using different versions of FreeSurfer... so they are slightly different... but we are talking about a usual difference of only ~hundreds of voxels... which is negligible.  But they are provided for people who want to keep their FreeSurfer tool versions absolutely consistent across their whole workflow.  

Does this help? Please let me know if you have any more questions.

**Comment by zqsha** [comment]
OK. I see. Thanks. After running the example_run_maTT2.sh, do I need to run mris_anatomical_stats in FreeSurfer? Because I want to get the mean values of cortical thickness, surface area and volume in each region of atlas for each subject.

**Comment by faskowit** [comment]
Oh yes indeed! These tools will not run FreeSurfer's `mris_anatomical_stats` function for you...but you can use `mris_anatomical_stats` on the output `.annot` files produced from the maTT2 process. So yes, run the maTT2, and then run that FreeSurfer function on the results. Let me know how goes!

**Comment by zqsha** [comment]
OK. Thanks. I will try to run a subject as an example. I will let you know the results.

**Comment by zqsha** [comment]
Hi, faskowit
I have run the maTT2.sh. It works well with no bugs. When I do the statistical analysis with mris_anatomical_stats, I used the following command:

mris_anatomical_stats -a /data/clusterfs/lag/users/zhisha/pd/sub20001/hcp-mmp-b/lh.hcp-mmp-b.annot -b sub20001 lh

An error reported: 
reading volume /usr/shared/apps/freesurfer/6.0.0/subjects/sub20001/mri/wm.mgz...
mghRead(/usr/shared/apps/freesurfer/6.0.0/subjects/sub20001/mri/wm.mgz, -1): could not open file

It's obvious that it pointed to the wrong path, but I found I could not specify the subject dir, though using mris_anatomical_stats -a /data/clusterfs/lag/users/zhisha/pd/sub20001/hcp-mmp-b/lh.hcp-mmp-b.annot -b /data/clusterfs/lag/users/zhisha/pd/sub20001 lh. On our server, /usr/shared/apps/freesurfer/6.0.0/ is the installation dir, we do not have permission to add files into that folder.

Do you have any suggestions about specifying the subject dir? I tried to first cd to the subject dir, but still does not work at all.

Thanks,
Zhiqiang

**Comment by faskowit** [comment]
hello!  Are you using the command line?  if so, with FreeSurfer you can set the subject directory by running this command before you run the `mris_anatomical_stats` command:
`export SUBJECTS_DIR=/data/clusterfs/lag/users/zhisha/pd/`
I am hopeful this should work.  FreeSurfer programs usually read this bash variable, `SUBJECTS_DIR`, to determine the paths to the images produced by `recon-all`

**Comment by zqsha** [comment]
Hi faskowit,
Yeah, I am using command line. Even though I added the export SUBJECTS_DIR=/data/clusterfs/lag/users/zhisha/pd/ in the front of the command, it still points to the installation dir (/usr/shared/apps/freesurfer/6.0.0/). Any ideas? Thanks

**Comment by zqsha** [comment]
I will check with the admin of our department. Maybe he locked some functions. Thanks. Anyway, it's really amazing toolbox, Hope to update more atlas. I am sure to cite and spread this cute toolbox. If I have any question, I would let you know.

**Comment by faskowit** [comment]
Humm...it is strange to be that program still points to the installation dir, even after you set the `SUBJECTS_DIR` to your specific path.   

I just took a look at some of my other scripts that apply `mris_anatomical_stats` and my call to them looks like this:  
```
${FREESURFER_HOME}/bin/mris_anatomical_stats \
	                -cortex ${subjFSDir}/label/${hemi}.cortex.label
	                -f ${outDir}/tmp.stats -b \
	                -a ${annot} \
                    ${subj} ${hemi} white
```
So maybe the program could benefit with the added parameters... like the `-cortex` command and specifying the `white` at the end?  I hope this helps!

**Comment by zqsha** [comment]
It works now. Thank you so much. I really appreciate, Amazing toolbox with an amazing guy.

**Comment by faskowit** [comment]
awesome awesome!  Thanks for testing this out!  Based on our discussion, I think soon I'd like to integrate this FreeSurfer call into the maTT2 scripts.
